alias: "Beregening: 018 - Schema 6"
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.schema_6_tuin_achter_30_minuten
    to: null
condition: []
action:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.beregening_grasveld_achtertuin_1_30_minuten
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.beregening_grasveld_2_30_minuten
mode: single
