alias: "Beregening: 029 - Run Druppelaars Zijkant/voortuin"
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.soil_moisture_4
    below: 25
  - platform: numeric_state
    entity_id:
      - sensor.soil_moisture_5
    below: 25
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id:
        - input_boolean.druppelaars_tuin_zijkant
    data: {}
mode: single
